'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {chairmanVoices,selectChairmanVoice} from '@/lib/chairman-voice';
import {ArrowUpRight,Download,FileText,Gavel,Info,RefreshCw,Volume2,VolumeX,ExternalLink,Copy,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {TOKEN,snapshot,money,joke,statusLabel,verdict,dateLabel,PERIOD_NAMES,type Period,type Meeting,type Cohort} from '@/lib/boardroom';
type HistoryPoint={at:string;cohorts:{id:string;flow:number|null;status:string}[];warning:string|null};

export default function Home(){
 const [period,setPeriod]=useState<Period>('1d'),[meeting,setMeeting]=useState<Meeting>(snapshot('1d')),[daily,setDaily]=useState<Meeting>(snapshot('1d'));
 const [history,setHistory]=useState<HistoryPoint[]>([]);
 const [loading,setLoading]=useState(false),[detail,setDetail]=useState<Cohort|null>(null),[report,setReport]=useState(false),[method,setMethod]=useState(false);
 const [speaking,setSpeaking]=useState(false),[feedback,setFeedback]=useState(''),[copied,setCopied]=useState(false),[speechSupported,setSpeechSupported]=useState(false);
 const [availableVoices,setAvailableVoices]=useState<SpeechSynthesisVoice[]>([]),[preferredVoiceURI,setPreferredVoiceURI]=useState('');
 const requestId=useRef(0),imageRef=useRef<HTMLImageElement>(null),logoRef=useRef<HTMLImageElement>(null),portraitRef=useRef<HTMLImageElement>(null);
 async function refresh(p:Period){const id=++requestId.current;setLoading(true);setFeedback('');try{const r=await fetch('/api/meeting?period='+p);if(!r.ok)throw Error();const data=await r.json() as Meeting;if(id!==requestId.current)return;setMeeting(data);if(p==='1d')setDaily(data);if(data.warning)setFeedback(data.warning);}catch{if(id===requestId.current){setMeeting(snapshot(p));setFeedback('Refresh unavailable. Showing the dated Nansen snapshot.');}}finally{if(id===requestId.current)setLoading(false);}}
 useEffect(()=>{void refresh(period);},[period]);
 useEffect(()=>{let cancelled=false;setHistory([]);void fetch('/api/history?period='+period).then(r=>r.ok?r.json():null).then((data:{points?:HistoryPoint[]}|null)=>{if(!cancelled&&Array.isArray(data?.points))setHistory(data.points);}).catch(()=>{});return()=>{cancelled=true;};},[period,meeting.asOf]);
 useEffect(()=>{if(!('speechSynthesis' in window))return;setSpeechSupported(true);
  setPreferredVoiceURI(window.localStorage.getItem('chairmanVoiceURI')??'');
  const updateVoices=()=>setAvailableVoices(chairmanVoices(window.speechSynthesis.getVoices()));
  updateVoices();window.speechSynthesis.addEventListener('voiceschanged',updateVoices);
  return()=>{window.speechSynthesis.removeEventListener('voiceschanged',updateVoices);window.speechSynthesis.cancel();};},[]);
 useEffect(()=>{if('speechSynthesis' in window){window.speechSynthesis.cancel();setSpeaking(false);}},[period]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_boner_meeting',title:'Read BONER meeting',description:'Read displayed cohort flows, timestamp, source and chairman summary.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {...meeting,verdict:verdict(meeting)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[meeting]);
 function speak(){
  if(speaking){window.speechSynthesis.cancel();setSpeaking(false);return;}
  const voice=selectChairmanVoice(window.speechSynthesis.getVoices(),preferredVoiceURI);
  if(!voice){setFeedback('No approved male voice is available in this browser. Install an English male system voice such as Guy, David or Daniel, then reload.');return;}
  window.speechSynthesis.cancel();
  const speech=new SpeechSynthesisUtterance('Board members. Eyes up. Let us discuss our exposure. '+verdict(meeting)+' '+meeting.cohorts.map(c=>c.name+'. '+joke(c)).join(' '));
  speech.voice=voice;speech.lang=voice.lang;speech.rate=.82;speech.pitch=.55;speech.volume=1;
  speech.onend=()=>setSpeaking(false);speech.onerror=()=>{setSpeaking(false);setFeedback('The chairman’s voice could not play. Please try again.');};
  window.speechSynthesis.speak(speech);setSpeaking(true);setFeedback('Chairman voice: '+voice.name);
 }

 async function openReport(){setReport(true);if(period!=='1d'){try{const r=await fetch('/api/meeting?period=1d');if(r.ok)setDaily(await r.json());}catch{}}}
 async function copyContract(){try{await navigator.clipboard.writeText(TOKEN);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setFeedback('Copy this contract: '+TOKEN);}}
 function downloadReport(){try{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1200;const ctx=canvas.getContext('2d');if(!ctx)throw Error();ctx.fillStyle='#0b1420';ctx.fillRect(0,0,1200,1200);
 if(imageRef.current?.complete){ctx.drawImage(imageRef.current,0,0,imageRef.current.naturalWidth,imageRef.current.naturalHeight*.742,0,0,1200,594);if(portraitRef.current?.complete){ctx.drawImage(portraitRef.current,192,35,168,160);}const g=ctx.createLinearGradient(0,300,0,600);g.addColorStop(0,'#0b142000');g.addColorStop(1,'#0b1420');ctx.fillStyle=g;ctx.fillRect(0,300,1200,300);}
 if(logoRef.current?.complete){ctx.save();ctx.beginPath();ctx.arc(79,621,24,0,Math.PI*2);ctx.clip();ctx.drawImage(logoRef.current,55,597,48,48);ctx.restore();}ctx.fillStyle='#e8f35b';ctx.font='bold 22px Arial';ctx.fillText('THE BONER BOARDROOM / DAILY BRIEFING',120,628);ctx.fillStyle='#ffffff';ctx.font='bold 66px Georgia';ctx.fillText('Morning Wood Report',55,709);ctx.fillStyle='#aab7c8';ctx.font='22px Arial';ctx.fillText('24-hour flows · '+dateLabel(daily.asOf)+' · '+(daily.source==='snapshot'?'Dated snapshot':'API observation'),55,752);
 daily.cohorts.forEach((c,i)=>{const x=55+i*380;ctx.fillStyle='#172433';ctx.fillRect(x,797,355,160);ctx.fillStyle='#e6ecf4';ctx.font='bold 22px Arial';ctx.fillText(c.name,x+22,832);ctx.fillStyle=c.flow!==null&&c.flow>0?'#dcec70':'#aab7c8';ctx.font='bold 40px Arial';ctx.fillText(c.status==='measured'?money(c.flow):c.status==='quiet'?'Quiet':'Unavailable',x+22,884);ctx.fillStyle='#aab7c8';ctx.font='18px Arial';ctx.fillText(statusLabel(c),x+22,921);});
 ctx.fillStyle='#ffffff';ctx.font='italic 27px Georgia';let line='',y=1010;for(const word of verdict(daily).split(' ')){if(ctx.measureText(line+word).width>1080){ctx.fillText(line,55,y);y+=36;line='';}line+=word+' ';}ctx.fillText(line,55,y);ctx.fillStyle='#aab7c8';ctx.font='18px Arial';ctx.fillText('Net flows are token movements, not confirmed buys. Cohorts can overlap.',55,1120);ctx.fillText('Powered by Nansen API · nansen.ai · BONER / Robinhood Chain',55,1155);
 canvas.toBlob(blob=>{if(!blob){setFeedback('Image export failed. Please try again.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='morning-wood-report-'+daily.asOf.slice(0,10)+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}catch{setFeedback('Unable to export the report image. Please try again.');}}
 const active=meeting.cohorts.filter(c=>c.status==='measured'&&c.flow!==0).length;
 const largestFlow=Math.max(1,...history.flatMap(p=>p.cohorts.map(c=>Math.abs(c.flow??0))));
 const historyLines=['smart','whale','public'].map(id=>history.map((point,i)=>{
  const flow=point.cohorts.find(c=>c.id===id)?.flow;
  return `${(i/Math.max(1,history.length-1)*100).toFixed(2)},${(50-(flow??0)/largestFlow*42).toFixed(2)}`;
 }).join(' '));
 return <div className="app-shell">
 <header className="masthead"><a className="brand" href="/" aria-label="BONER Boardroom home"><span className="brand-icon"><Image ref={logoRef} src="/api/art/boner-logo" alt="BONER sunglasses and laurel logo" width={52} height={52} unoptimized priority/></span><span>BONER<span className="brand-small">BOARDROOM</span></span></a><div className="header-right"><span className="chain-label">ROBINHOOD CHAIN</span><Button onClick={openReport} className="report-button"><FileText/> Morning Wood Report <ArrowUpRight/></Button></div></header>
 <main><div className="page-intro"><div><div className="eyebrow">AN EXTRAORDINARY MEETING OF THE HOLDERS</div><h1>Let’s discuss your <em>exposure.</em></h1></div><button className="text-action" onClick={()=>setMethod(true)} aria-label="How this works"><Info size={16}/> How this works</button></div>
 <div className="meeting-toolbar"><div className="session-label"><Gavel size={16}/><strong>Meeting in session</strong><span className="source-pill">{meeting.source==='snapshot'?'DATED SNAPSHOT':'NANSEN API'}</span></div><div className="time-controls"><span className="muted">Lookback</span><Tabs value={period} onValueChange={v=>{setPeriod(v as Period);setMeeting(snapshot(v as Period));setDetail(null);}}><TabsList aria-label="Meeting lookback"><TabsTrigger value="1h">1h</TabsTrigger><TabsTrigger value="1d">24h</TabsTrigger><TabsTrigger value="7d">7d</TabsTrigger></TabsList></Tabs><Button variant="ghost" size="icon" aria-label="Refresh meeting" disabled={loading} onClick={()=>refresh(period)}><RefreshCw size={17} className={loading?'spin':''}/></Button></div></div>
 <div className="main-grid"><section className="room" aria-label="Interactive boardroom"><div className="room-art"><Image ref={imageRef} src="/api/art/boardroom-v3" alt="The BONER marble statue joins a brain and whale at the boardroom table, with the official portrait in a gold frame on the wall." fill unoptimized priority sizes="(max-width: 820px) 100vw, 65vw"/><div className="room-shade"/><a className="portrait-link" href="https://boneronlong.xyz/" target="_blank" rel="noopener noreferrer" aria-label="Visit the official BONER website through the framed portrait" title="Visit BONER official website"><span className="portrait-photo"><Image ref={portraitRef} src="/api/art/boner-portrait-v2" alt="Official BONER portrait in a gold frame" fill unoptimized sizes="15vw"/></span><span className="portrait-caption">Visit BONER ↗</span></a><div className="room-caption"><span>THE DELEGATIONS</span><span>{active}/3 reporting measurable net flows</span></div><div className="seat-buttons">{meeting.cohorts.map((c,i)=><button key={c.id} className={'seat seat-'+i+' '+(c.flow!==null&&c.flow>0?'positive':'')} onClick={()=>setDetail(c)}><span className="seat-name">{c.name}</span><span>{c.status==='measured'?money(c.flow):c.status==='missing'?'No data':'Keeping quiet'} <ArrowUpRight size={14}/></span></button>)}</div></div><div className="chairman"><div className="chairman-icon"><Gavel size={24}/></div><div><div className="eyebrow">A WORD FROM THE CHAIRMAN</div><p key={period}>{verdict(meeting)}</p></div>{speechSupported&&<div className="chairman-audio"><label className="voice-choice">Voice <select aria-label="Chairman voice" value={availableVoices.some(v=>v.voiceURI===preferredVoiceURI)?preferredVoiceURI:availableVoices[0]?.voiceURI??''} onChange={e=>{window.speechSynthesis.cancel();setSpeaking(false);setPreferredVoiceURI(e.target.value);window.localStorage.setItem('chairmanVoiceURI',e.target.value);}}>{availableVoices.length?availableVoices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name}</option>):<option value="">No male voice</option>}</select></label><button className="audio" onClick={speak} aria-label={speaking?'Stop chairman narration':'Hear the chairman'}>{speaking?<VolumeX/>:<Volume2/>}</button></div>}</div></section>
 <aside className="roll-call"><div className="panel-heading"><h2>Roll call</h2><span>{PERIOD_NAMES[period]}</span></div><p className="roll-sub">Who’s showing up for BONER?</p>{meeting.cohorts.map((c,i)=><button key={c.id} className="cohort-card" onClick={()=>setDetail(c)}><div className="cohort-head"><span className={'avatar avatar-'+i}>{i===2?<Image src="/api/art/boner-logo" alt="BONER" width={40} height={40} unoptimized/>:['🧠','🐋'][i]}</span><div><h3>{c.name}</h3><span>{c.role}</span></div><ArrowUpRight size={17}/></div><div className={'flow-value '+(c.flow!==null&&c.flow>0?'positive':c.flow!==null&&c.flow<0?'negative':'')}>{c.status==='measured'?money(c.flow):c.status==='missing'?'Unavailable':'Quiet'}<span>{c.wallets!==null?c.wallets+' active wallets':'Wallet count not reported'}</span></div><div className="flow-label">{statusLabel(c)}</div><p>{joke(c)}</p></button>)}</aside></div>
 <div className="data-status" role="status"><span>{loading?'Checking Nansen…':`${meeting.source==='snapshot'?'Snapshot captured':'Observation retrieved'} ${dateLabel(meeting.asOf)}`}</span><span>{feedback||(meeting.source==='snapshot'?'Real Nansen observations. Automatic updates are not connected yet.':'Cached for up to 4 minutes; upstream data may lag.')}</span></div>
 <section className="history-panel" aria-label="Observed token flow history"><div className="panel-heading"><h2>Flow history</h2><span>{PERIOD_NAMES[period]} · {history.length} observations</span></div><p className="footnote">Time-stamped Nansen observations collected while the boardroom is live. Each line follows a delegation’s net flow in the selected window.</p>{history.length>1?<><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="History of Smart Trader, Whale and Public Figure net flows"><line x1="0" x2="100" y1="50" y2="50" stroke="#4b5868" strokeDasharray="2 2"/>{historyLines.map((points,i)=><polyline key={i} points={points} fill="none" stroke={['#e8f35b','#65b9da','#e6a875'][i]} strokeWidth="1.3" vectorEffect="non-scaling-stroke"/>)}</svg><div className="history-key"><span>● Smart Traders</span><span>● Whales</span><span>● Public Figures</span></div><div className="history-range"><span>{dateLabel(history[0].at)}</span><span>{dateLabel(history[history.length-1].at)}</span></div></>:<p className="history-empty">The timeline will appear after the second scheduled observation.</p>}</section>
 <div className="bottom-grid"><section className="trade-panel"><div className="panel-heading"><h2>Meanwhile, on the trading floor</h2><span>24H SNAPSHOT</span></div><div className="trade-stats"><div><span>DEX buy volume</span><strong className="positive">$374.3K</strong><small>590 buys · 284 buyers</small></div><div><span>DEX sell volume</span><strong>$327.0K</strong><small>688 sells · 286 sellers</small></div><div><span>Token holders</span><strong>11,346</strong><small>Reported by Nansen</small></div></div><div className="volume-bar" aria-label="Buy volume 53.4 percent; sell volume 46.6 percent"><span style={{width:'53.4%'}}/></div><p className="footnote">Actual DEX activity, separate from cohort transfers. Captured Sep 25, 2026 at 9:13 a.m. PT. These launch statistics do not auto-refresh.</p></section><section className="daily-teaser"><div className="eyebrow">THE DAILY SHARE CARD</div><h2>Morning Wood<br/><em>Report.</em></h2><p>Fresh minutes. Questionable professionalism.</p><Button onClick={openReport}>Prepare today’s briefing <ArrowUpRight size={16}/></Button></section></div></main>
 <footer><div><a href="https://nansen.ai/" target="_blank" rel="noreferrer">Powered by <strong>Nansen API</strong> <ExternalLink size={13}/></a><p>Community satire. Token flows describe activity, not investment advice.</p></div><button onClick={copyContract} className="contract">BONER · 0x9809…11e18 {copied?<Check size={14}/>:<Copy size={14}/>}</button></footer>
 <Dialog open={detail!==null} onOpenChange={open=>{if(!open)setDetail(null);}}><DialogContent className="detail-dialog"><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.role} · {PERIOD_NAMES[period]}</DialogDescription>{detail&&<><div className="detail-number">{detail.status==='measured'?money(detail.flow):statusLabel(detail)}</div><p>{joke(detail)}</p><dl><div><dt>Metric</dt><dd>Net token flow, USD</dd></div><div><dt>Active wallets</dt><dd>{detail.wallets??'Not reported'}</dd></div><div><dt>Captured</dt><dd>{dateLabel(meeting.asOf)}</dd></div><div><dt>Source</dt><dd>Nansen Flow Intelligence</dd></div></dl><p className="footnote">{detail.status==='quiet'?'Nansen’s snapshot summary reported no significant net flow. This does not prove there were no trades or no holders. ':detail.status==='missing'?'No usable data was returned. Missing data is not zero. ':''}Transfers can include movements unrelated to buying. Cohorts may overlap; counts must not be summed as unique holders.</p><a className="source-link" href="https://docs.nansen.ai/api/token-god-mode/flow-intelligence" target="_blank" rel="noreferrer">Read the data methodology <ExternalLink size={14}/></a></>}</DialogContent></Dialog>
 <Dialog open={report} onOpenChange={setReport}><DialogContent className="report-dialog"><DialogTitle>Morning Wood Report</DialogTitle><DialogDescription>A shareable 24-hour briefing. Every card includes its data timestamp.</DialogDescription><div className="share-card"><div className="eyebrow">THE BONER BOARDROOM · DAILY BRIEFING</div><h2>Morning Wood<br/><em>Report.</em></h2><span>{dateLabel(daily.asOf)} · {daily.source==='snapshot'?'Dated snapshot':'API observation'}</span><div className="share-metrics">{daily.cohorts.map(c=><div key={c.id}><small>{c.name}</small><strong>{c.status==='measured'?money(c.flow):c.status==='quiet'?'Quiet':'No data'}</strong><small>{statusLabel(c)}</small></div>)}</div><p>“{verdict(daily)}”</p><div className="share-credit">Powered by Nansen API · Net flows ≠ confirmed buys</div></div><Button onClick={downloadReport}><Download size={16}/> Download PNG</Button><p className="footnote">Download only. Nothing is posted to X or sent to anyone.</p></DialogContent></Dialog>
 <Dialog open={method} onOpenChange={setMethod}><DialogContent className="detail-dialog"><DialogTitle>Serious data. Unscheduled innuendo.</DialogTitle><DialogDescription>How the BONER Boardroom reads the room.</DialogDescription><p>The fictional delegates represent Nansen’s Smart Trader, Whale and Public Figure cohorts. Commentary follows net token flows in your selected window.</p><ul className="method-list"><li><strong>Positive:</strong> more token value entered the cohort than left.</li><li><strong>Negative:</strong> more token value left than entered.</li><li><strong>Quiet:</strong> the captured summary reported no significant net flow. Exact values and wallet counts were not provided.</li><li><strong>Unavailable:</strong> no usable data; never interpreted as zero.</li></ul><p>Cohorts can overlap. Transfers are not necessarily purchases. No price forecast or conviction score is implied.</p><p className="footnote">Initial observations were retrieved through Nansen on Sep 25, 2026. Snapshot figures are rounded. The share card always uses 24 hours, even when you view seven days.</p><a className="source-link" href="https://docs.nansen.ai/api/token-god-mode/flow-intelligence" target="_blank" rel="noreferrer">Nansen documentation <ExternalLink size={14}/></a></DialogContent></Dialog>
 </div>;
}
