'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {ArrowUpRight,Download,FileText,Gavel,Info,RefreshCw,ExternalLink,Copy,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {TOKEN,snapshot,money,joke,statusLabel,verdict,dateLabel,PERIOD_NAMES,type Period,type Meeting,type Cohort} from '@/lib/boardroom';
import {holderUsdMetrics,type HolderCount,type TopHolders} from '@/lib/nansen-usage';
type HistoryPoint={at:string;cohorts:{id:string;flow:number|null;status:string}[];warning:string|null};
const POOL_MANAGER='0x8366a39cc670b4001a1121b8f6a443a643e40951';

export default function Home(){
 const [period,setPeriod]=useState<Period>('1d'),[meeting,setMeeting]=useState<Meeting>(snapshot('1d')),[daily,setDaily]=useState<Meeting>(snapshot('1d'));
 const [history,setHistory]=useState<HistoryPoint[]>([]);
 const [topHolders,setTopHolders]=useState<TopHolders|null>(null),[holdersWarning,setHoldersWarning]=useState('');
 const [holderHistory,setHolderHistory]=useState<{asOf:string;totalTokens:number;change24h:number|null;change24hUsd:number|null;totalValueUsd:number|null;count:number}[]>([]);
 const [holderCount,setHolderCount]=useState<HolderCount|null>(null),[holderCountWarning,setHolderCountWarning]=useState('');
 const [holderCountHistory,setHolderCountHistory]=useState<HolderCount[]>([]);
 const [loading,setLoading]=useState(false),[detail,setDetail]=useState<Cohort|null>(null),[report,setReport]=useState(false),[method,setMethod]=useState(false);
 const [feedback,setFeedback]=useState(''),[copied,setCopied]=useState(false);
 const requestId=useRef(0),imageRef=useRef<HTMLImageElement>(null),logoRef=useRef<HTMLImageElement>(null);
 async function refresh(p:Period){const id=++requestId.current;setLoading(true);setFeedback('');try{const r=await fetch('/api/meeting?period='+p);if(!r.ok)throw Error();const data=await r.json() as Meeting;if(id!==requestId.current)return;setMeeting(data);if(p==='1d')setDaily(data);if(data.warning)setFeedback(data.warning);}catch{if(id===requestId.current){setMeeting(snapshot(p));setFeedback('Refresh unavailable. Showing the dated Nansen snapshot.');}}finally{if(id===requestId.current)setLoading(false);}}
 useEffect(()=>{void refresh(period);},[period]);
 useEffect(()=>{void fetch('/api/top-holders').then(r=>r.json()).then((data:{snapshot:TopHolders|null;warning?:string})=>{setTopHolders(data.snapshot);setHoldersWarning(data.warning??'');}).catch(()=>setHoldersWarning('Top holder data is temporarily unavailable.'));},[]);
 useEffect(()=>{void fetch('/api/top-holders/history').then(r=>r.ok?r.json():null).then((data:{points?:{asOf:string;totalTokens:number;change24h:number|null;change24hUsd:number|null;totalValueUsd:number|null;count:number}[]}|null)=>{if(Array.isArray(data?.points))setHolderHistory(data.points);}).catch(()=>{});},[topHolders?.asOf]);
 useEffect(()=>{void fetch('/api/holder-count').then(r=>r.json()).then((data:{snapshot:HolderCount|null;warning?:string})=>{setHolderCount(data.snapshot);setHolderCountWarning(data.warning??'');}).catch(()=>setHolderCountWarning('Holder count is temporarily unavailable.'));},[]);
 useEffect(()=>{void fetch('/api/holder-count/history').then(r=>r.ok?r.json():null).then((data:{points?:HolderCount[]}|null)=>{if(Array.isArray(data?.points))setHolderCountHistory(data.points);}).catch(()=>{});},[holderCount?.asOf]);
 useEffect(()=>{let cancelled=false;setHistory([]);void fetch('/api/history?period='+period).then(r=>r.ok?r.json():null).then((data:{points?:HistoryPoint[]}|null)=>{if(!cancelled&&Array.isArray(data?.points))setHistory(data.points);}).catch(()=>{});return()=>{cancelled=true;};},[period,meeting.asOf]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_boner_meeting',title:'Read BONER meeting',description:'Read displayed cohort flows, timestamp, source and chairman summary.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {...meeting,verdict:verdict(meeting)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[meeting]);
 async function openReport(){setReport(true);if(period!=='1d'){try{const r=await fetch('/api/meeting?period=1d');if(r.ok)setDaily(await r.json());}catch{}}}
 async function copyContract(){try{await navigator.clipboard.writeText(TOKEN);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setFeedback('Copy this contract: '+TOKEN);}}
 function downloadReport(){try{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1200;const ctx=canvas.getContext('2d');if(!ctx)throw Error();ctx.fillStyle='#0b1420';ctx.fillRect(0,0,1200,1200);
 if(imageRef.current?.complete){ctx.drawImage(imageRef.current,0,0,imageRef.current.naturalWidth,imageRef.current.naturalWidth*594/1200,0,0,1200,594);const g=ctx.createLinearGradient(0,300,0,600);g.addColorStop(0,'#0b142000');g.addColorStop(1,'#0b1420');ctx.fillStyle=g;ctx.fillRect(0,300,1200,300);}
 if(logoRef.current?.complete){ctx.save();ctx.beginPath();ctx.arc(79,621,24,0,Math.PI*2);ctx.clip();ctx.drawImage(logoRef.current,55,597,48,48);ctx.restore();}ctx.fillStyle='#e8f35b';ctx.font='bold 22px Arial';ctx.fillText('THE BONER BOARDROOM / DAILY BRIEFING',120,628);ctx.fillStyle='#ffffff';ctx.font='bold 66px Georgia';ctx.fillText('Morning Wood Report',55,709);ctx.fillStyle='#aab7c8';ctx.font='22px Arial';ctx.fillText('24-hour flows · '+dateLabel(daily.asOf)+' · '+(daily.source==='snapshot'?'Dated snapshot':'API observation'),55,752);
 daily.cohorts.forEach((c,i)=>{const x=55+i*285;ctx.fillStyle='#172433';ctx.fillRect(x,797,270,160);ctx.fillStyle='#e6ecf4';ctx.font='bold 22px Arial';ctx.fillText(c.name,x+22,832);ctx.fillStyle=c.flow!==null&&c.flow>0?'#dcec70':'#aab7c8';ctx.font='bold 34px Arial';ctx.fillText(c.status==='measured'?money(c.flow):c.status==='quiet'?'Quiet':'Unavailable',x+22,884);ctx.fillStyle='#aab7c8';ctx.font='18px Arial';ctx.fillText(statusLabel(c),x+22,921);});
 ctx.fillStyle='#ffffff';ctx.font='italic 27px Georgia';let line='',y=1010;for(const word of verdict(daily).split(' ')){if(ctx.measureText(line+word).width>1080){ctx.fillText(line,55,y);y+=36;line='';}line+=word+' ';}ctx.fillText(line,55,y);ctx.fillStyle='#aab7c8';ctx.font='18px Arial';ctx.fillText('Net flows are token movements, not confirmed buys. Cohorts can overlap.',55,1120);ctx.fillText('Powered by Nansen API · nansen.ai · BONER / Robinhood Chain',55,1155);
 canvas.toBlob(blob=>{if(!blob){setFeedback('Image export failed. Please try again.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='morning-wood-report-'+daily.asOf.slice(0,10)+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}catch{setFeedback('Unable to export the report image. Please try again.');}}
 const tokenNumber=(value:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(value);
 const tokenChange=(value:number|null)=>value===null?'Unavailable':(value>0?'+':'')+tokenNumber(value);
 const holderMetrics=topHolders?holderUsdMetrics(topHolders):null;
 const poolManagerRank=topHolders?.wallets.findIndex(w=>w.address.toLowerCase()===POOL_MANAGER)??-1;
 const previousHolderCount=holderCountHistory.length>1?holderCountHistory[holderCountHistory.length-2]:null;
 const holderCountChange=holderCount&&previousHolderCount?holderCount.totalHolders-previousHolderCount.totalHolders:null;
 const holderMin=Math.min(...holderCountHistory.map(p=>p.totalHolders));
 const holderMax=Math.max(...holderCountHistory.map(p=>p.totalHolders));
 const holderFirstAt=holderCountHistory.length?Date.parse(holderCountHistory[0].asOf):0;
 const holderLastAt=holderCountHistory.length?Date.parse(holderCountHistory[holderCountHistory.length-1].asOf):0;
 const holderCountLine=holderCountHistory.map(p=>`${((Date.parse(p.asOf)-holderFirstAt)/Math.max(1,holderLastAt-holderFirstAt)*100).toFixed(2)},${holderMin===holderMax?50:(85-(p.totalHolders-holderMin)/(holderMax-holderMin)*70).toFixed(2)}`).join(' ');
 const largestFlow=Math.max(1,...history.flatMap(p=>p.cohorts.map(c=>Math.abs(c.flow??0))));
 const historyLines=['smart','whale','public','exchange'].map(id=>history.flatMap((point,i)=>{
  const flow=point.cohorts.find(c=>c.id===id)?.flow;
  return typeof flow==='number'?[`${(i/Math.max(1,history.length-1)*100).toFixed(2)},${(50-flow/largestFlow*42).toFixed(2)}`]:[];
 }).join(' '));
 return <div className="app-shell">
 <header className="masthead"><a className="brand" href="/" aria-label="BONER Boardroom home"><span className="brand-icon"><Image ref={logoRef} src="/api/art/boner-logo" alt="BONER sunglasses and laurel logo" width={52} height={52} unoptimized priority/></span><span>BONER<span className="brand-small">BOARDROOM</span></span></a><div className="header-right"><span className="chain-label">ROBINHOOD CHAIN</span><Button onClick={openReport} className="report-button"><FileText/> Morning Wood Report <ArrowUpRight/></Button></div></header>
 <main><div className="page-intro"><div><div className="eyebrow">AN EXTRAORDINARY MEETING OF THE HOLDERS</div><h1>Let’s discuss your <em>exposure.</em></h1></div><button className="text-action" onClick={()=>setMethod(true)} aria-label="How this works"><Info size={16}/> How this works</button></div>
 <div className="meeting-toolbar"><div className="session-label"><Gavel size={16}/><strong>Meeting in session</strong><span className="source-pill">{meeting.source==='snapshot'?'DATED SNAPSHOT':'NANSEN API'}</span></div><div className="time-controls"><span className="muted">Lookback</span><Tabs value={period} onValueChange={v=>{setPeriod(v as Period);setMeeting(snapshot(v as Period));setDetail(null);}}><TabsList aria-label="Meeting lookback"><TabsTrigger value="1h">1h</TabsTrigger><TabsTrigger value="1d">24h</TabsTrigger><TabsTrigger value="7d">7d</TabsTrigger></TabsList></Tabs><Button variant="ghost" size="icon" aria-label="Refresh meeting" disabled={loading} onClick={()=>refresh(period)}><RefreshCw size={17} className={loading?'spin':''}/></Button></div></div>
 <div className="main-grid"><section className="room" aria-label="Interactive boardroom"><div className="room-art"><Image ref={imageRef} src="/boardroom-v4.webp" alt="The BONER marble statue joins a brain and whale at the boardroom table, with the official portrait in a gold frame on the wall." fill unoptimized priority sizes="(max-width: 820px) 100vw, 65vw"/><div className="room-shade"/><a className="portrait-link" href="https://boneronlong.xyz/" target="_blank" rel="noopener noreferrer" aria-label="Visit the official BONER website through the framed portrait" title="Visit BONER official website"><span className="portrait-caption">Visit BONER ↗</span></a></div></section>
 <aside className="roll-call"><div className="panel-heading"><h2>Roll call</h2><span>{PERIOD_NAMES[period]}</span></div><p className="roll-sub">Cohort net token flow in USD. Nansen’s holder balances and 24h wallet changes use a different measure; Public Figures can have changing balances while this flow reads $0. Tap Refresh for a new observation.</p>{meeting.cohorts.map((c,i)=><button key={c.id} className="cohort-card" onClick={()=>setDetail(c)}><div className="cohort-head"><span className={'avatar avatar-'+i}>{i===2?<Image src="/api/art/boner-logo" alt="BONER" width={40} height={40} unoptimized/>:['🧠','🐋','', '🏦'][i]}</span><div><h3>{c.name}</h3><span>{c.role}</span></div><ArrowUpRight size={17}/></div><div className={'flow-value '+(c.flow!==null&&c.flow>0?'positive':c.flow!==null&&c.flow<0?'negative':'')}>{c.status==='measured'?money(c.flow):c.status==='missing'?'Unavailable':'Quiet'}<span>{c.id==='exchange'?'Wallet count not tracked':c.wallets!==null?c.wallets+' flow wallets':'Flow wallet count not reported'}</span></div><div className="flow-label">{statusLabel(c)}</div><p>{joke(c)}</p></button>)}</aside></div>
 <div className="data-status" role="status"><span>{loading?'Checking Nansen…':`${meeting.source==='snapshot'?'Snapshot captured':'Observation retrieved'} ${dateLabel(meeting.asOf)}`}</span><span>{feedback||(meeting.source==='snapshot'?'Real Nansen observations. Automatic updates are not connected yet.':'Refresh intervals vary by selected window; upstream data may lag.')}</span></div>
 <section className="history-panel" aria-label="Observed token flow history"><div className="panel-heading"><h2>Flow history</h2><span>{PERIOD_NAMES[period]} · {history.length} observations</span></div><p className="footnote">Time-stamped Nansen observations collected while the boardroom is live. Each line follows a delegation’s net flow in the selected window.</p>{history.length>1?<><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="History of Smart Trader, Whale, Public Figure and Exchange net flows"><line x1="0" x2="100" y1="50" y2="50" stroke="#4b5868" strokeDasharray="2 2"/>{historyLines.map((points,i)=><polyline key={i} points={points} fill="none" stroke={['#e8f35b','#65b9da','#e6a875','#ba9afa'][i]} strokeWidth="1.3" vectorEffect="non-scaling-stroke"/>)}</svg><div className="history-key"><span>● Smart Traders</span><span>● Whales</span><span>● Public Figures</span><span>● Exchanges</span></div><div className="history-range"><span>{dateLabel(history[0].at)}</span><span>{dateLabel(history[history.length-1].at)}</span></div></>:<p className="history-empty">The timeline will appear after the second daily observation.</p>}</section>
 <section className="holders-panel" aria-label="Top 40 BONER holders">
 <div className="panel-heading"><h2>Top 40 wallets</h2><span>{topHolders?dateLabel(topHolders.asOf):'Awaiting first observation'}</span></div>
 <p className="footnote">Largest BONER balances from Nansen Holders. USD values use the price implied by this snapshot. The 24h change values today’s token balance change at that price; it is not USD net flow, confirmed buys or profit. Top 40 membership can change between snapshots.</p>
 {topHolders&&holderMetrics?<>
  <div className="holders-stats">
   <div><small>Combined balance</small><strong>{tokenNumber(topHolders.totalTokens)} BONER</strong></div>
   <div><small>Combined value · USD</small><strong>{holderMetrics.totalValueUsd===null?'Unavailable':money(holderMetrics.totalValueUsd).replace(/^\+/,'')}</strong></div>
   <div><small>24h balance change · USD est.</small><strong className={holderMetrics.change24hUsd!==null&&holderMetrics.change24hUsd<0?'negative':'positive'}>{holderMetrics.change24hUsd===null?'Unavailable':money(holderMetrics.change24hUsd)}</strong></div>
   <div><small>Wallets adding / reducing</small><strong>{holderMetrics.adding===null?'Unavailable':`${holderMetrics.adding} / ${holderMetrics.reducing}`}</strong></div>
  </div>
  <p className="footnote">{topHolders.count} of 40 wallets returned · Unchanged wallets are excluded from the adding / reducing count.</p>
  {poolManagerRank>=0&&<p className="footnote pool-manager-note"><strong>Wallet #{poolManagerRank+1}: Uniswap v4 Pool Manager.</strong> This address is a liquidity pool contract, not an individual trader. Its BONER balance is included in the Top 40 totals. <a href="https://github.com/Uniswap/UniswapX/blob/main/playbook/chains/robinhood.md" target="_blank" rel="noopener noreferrer">Uniswap deployment notes ↗</a></p>}
  <details><summary>View wallet balances</summary><div className="holders-table-wrap"><table><thead><tr><th>Rank</th><th>Wallet</th><th>BONER balance</th><th>24h change · USD est.</th></tr></thead><tbody>{topHolders.wallets.map((w,i)=><tr key={w.address}><td>{i+1}</td><td title={w.address}>{w.address.slice(0,8)}…{w.address.slice(-6)}{w.address.toLowerCase()===POOL_MANAGER&&<span className="wallet-tag">Uniswap: Pool Manager</span>}</td><td>{tokenNumber(w.tokenAmount)}</td><td>{holderMetrics.priceUsd===null||w.balanceChange24h===null?'Unavailable':money(w.balanceChange24h*holderMetrics.priceUsd)}</td></tr>)}</tbody></table></div></details>
  {holderHistory.length>0&&<details><summary>Daily balance history ({holderHistory.length})</summary><div className="holders-table-wrap"><table><thead><tr><th>Observed</th><th>Wallets</th><th>Combined BONER</th><th>Combined USD</th><th>24h change · USD est.</th></tr></thead><tbody>{holderHistory.map(point=><tr key={point.asOf}><td>{dateLabel(point.asOf)}</td><td>{point.count}</td><td>{tokenNumber(point.totalTokens)}</td><td>{point.totalValueUsd===null?'Unavailable':money(point.totalValueUsd).replace(/^\+/,'')}</td><td>{point.change24hUsd===null?'Unavailable':money(point.change24hUsd)}</td></tr>)}</tbody></table></div></details>}
 </>:<p className="history-empty">{holdersWarning||'The first holder observation is being collected.'}</p>}
 {topHolders&&holdersWarning&&<p className="footnote">{holdersWarning}</p>}
 </section>
 <section className="holder-growth-panel" aria-label="Daily BONER holder count history">
  <div className="panel-heading"><h2>Token holder history</h2><span>DAILY NANSEN OBSERVATIONS</span></div>
  <p className="footnote">Total BONER holder addresses reported by Nansen Token Information, separate from the Top 40 wallets. One observation is collected about every 24 hours; missing days are not filled in.</p>
  {holderCount?<>
   <div className="holder-growth-stats"><div><small>Total holders</small><strong>{tokenNumber(holderCount.totalHolders)}</strong><span>Observed {dateLabel(holderCount.asOf)}</span></div><div><small>Since previous observation</small><strong className={holderCountChange!==null&&holderCountChange<0?'negative':'positive'}>{holderCountChange===null?'Pending':tokenChange(holderCountChange)}</strong><span>{previousHolderCount?`From ${dateLabel(previousHolderCount.asOf)}`:'The next daily observation will show a change.'}</span></div></div>
   {holderCountHistory.length>1?<><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="History of BONER token holder count"><polyline points={holderCountLine} fill="none" stroke="#e8f35b" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div className="history-range"><span>{dateLabel(holderCountHistory[0].asOf)}</span><span>{dateLabel(holderCountHistory[holderCountHistory.length-1].asOf)}</span></div></>:<p className="history-empty">The trend appears after the second daily observation.</p>}
   {holderCountHistory.length>0&&<details><summary>Daily observations ({holderCountHistory.length})</summary><div className="holders-table-wrap"><table><thead><tr><th>Observed</th><th>Total holders</th><th>Change</th></tr></thead><tbody>{holderCountHistory.map((point,i)=><tr key={point.asOf}><td>{dateLabel(point.asOf)}</td><td>{tokenNumber(point.totalHolders)}</td><td>{i?tokenChange(point.totalHolders-holderCountHistory[i-1].totalHolders):'—'}</td></tr>)}</tbody></table></div></details>}
  </>:<p className="history-empty">{holderCountWarning||'The first holder count is being collected.'}</p>}
  {holderCount&&holderCountWarning&&<p className="footnote">{holderCountWarning}</p>}
 </section><div className="bottom-grid"><section className="trade-panel"><div className="panel-heading"><h2>Meanwhile, on the trading floor</h2><span>24H SNAPSHOT</span></div><div className="trade-stats"><div><span>DEX buy volume</span><strong className="positive">$374.3K</strong><small>590 buys · 284 buyers</small></div><div><span>DEX sell volume</span><strong>$327.0K</strong><small>688 sells · 286 sellers</small></div><div><span>Token holders</span><strong>{holderCount?tokenNumber(holderCount.totalHolders):'—'}</strong><small>{holderCount?`Updated ${dateLabel(holderCount.asOf)}`:'Awaiting daily Nansen observation'}</small></div></div><div className="volume-bar" aria-label="Buy volume 53.4 percent; sell volume 46.6 percent"><span style={{width:'53.4%'}}/></div><p className="footnote">Actual DEX activity, separate from cohort transfers. Captured Sep 25, 2026 at 9:13 a.m. PT. DEX launch statistics do not auto-refresh. The holder count above updates daily.</p></section><section className="daily-teaser"><div className="eyebrow">THE DAILY SHARE CARD</div><h2>Morning Wood<br/><em>Report.</em></h2><p>Fresh minutes. Questionable professionalism.</p><Button onClick={openReport}>Prepare today’s briefing <ArrowUpRight size={16}/></Button></section></div></main>
 <footer><div><a href="https://nansen.ai/" target="_blank" rel="noreferrer">Powered by <strong>Nansen API</strong> <ExternalLink size={13}/></a><p>Community satire. Token flows describe activity, not investment advice.</p></div><button onClick={copyContract} className="contract">BONER · 0x9809…11e18 {copied?<Check size={14}/>:<Copy size={14}/>}</button></footer>
 <Dialog open={detail!==null} onOpenChange={open=>{if(!open)setDetail(null);}}><DialogContent className="detail-dialog"><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.role} · {PERIOD_NAMES[period]}</DialogDescription>{detail&&<><div className="detail-number">{detail.status==='measured'?money(detail.flow):statusLabel(detail)}</div><p>{joke(detail)}</p><dl><div><dt>Metric</dt><dd>Net token flow, USD</dd></div><div><dt>Flow wallets</dt><dd>{detail.id==='exchange'?'Not tracked':detail.wallets??'Not reported'}</dd></div><div><dt>Retrieved</dt><dd>{dateLabel(meeting.asOf)}</dd></div><div><dt>Source</dt><dd>Nansen Flow Intelligence</dd></div></dl><p className="footnote">{detail.status==='quiet'?'Nansen’s snapshot summary reported no significant net flow. This does not prove there were no trades or no holders. ':detail.status==='missing'?'No usable data was returned. Missing data is not zero. ':''}Flow wallets are not the number of current holders. Nansen’s Holders view may show 24h wallet balance changes even when Flow Intelligence reports zero net flow and zero flow wallets. Transfers can include movements unrelated to buying. Cohorts may overlap; counts must not be summed as unique holders.</p><a className="source-link" href="https://docs.nansen.ai/api/token-god-mode/flow-intelligence" target="_blank" rel="noreferrer">Read the data methodology <ExternalLink size={14}/></a></>}</DialogContent></Dialog>
 <Dialog open={report} onOpenChange={setReport}><DialogContent className="report-dialog"><DialogTitle>Morning Wood Report</DialogTitle><DialogDescription>A shareable 24-hour briefing. Every card includes its data timestamp.</DialogDescription><div className="share-card"><div className="eyebrow">THE BONER BOARDROOM · DAILY BRIEFING</div><h2>Morning Wood<br/><em>Report.</em></h2><span>{dateLabel(daily.asOf)} · {daily.source==='snapshot'?'Dated snapshot':'API observation'}</span><div className="share-metrics">{daily.cohorts.map(c=><div key={c.id}><small>{c.name}</small><strong>{c.status==='measured'?money(c.flow):c.status==='quiet'?'Quiet':'No data'}</strong><small>{statusLabel(c)}</small></div>)}</div><p>“{verdict(daily)}”</p><div className="share-credit">Powered by Nansen API · Net flows ≠ confirmed buys</div></div><Button onClick={downloadReport}><Download size={16}/> Download PNG</Button><p className="footnote">Download only. Nothing is posted to X or sent to anyone.</p></DialogContent></Dialog>
 <Dialog open={method} onOpenChange={setMethod}><DialogContent className="detail-dialog"><DialogTitle>Serious data. Unscheduled innuendo.</DialogTitle><DialogDescription>How the BONER Boardroom reads the room.</DialogDescription><p>The fictional delegates represent Nansen’s Smart Trader, Whale, Public Figure and Exchange cohorts. Commentary follows net token flows in your selected window. Nansen’s “What Are Holders Doing?” chart instead shows token balances over a selected period, often 30 days. Its 24h Chg column shows changes in individual wallet balances, which can differ from cohort net flow. A zero flow-wallet count is not a count of holders. Warnings about unrelated exchange or fresh-wallet fields do not invalidate Public Figures data.</p><ul className="method-list"><li><strong>Positive:</strong> more token value entered the cohort than left.</li><li><strong>Negative:</strong> more token value left than entered.</li><li><strong>Zero flow:</strong> no net movement reported in this window; zero flow wallets does not mean zero holders.</li><li><strong>Quiet:</strong> the captured summary reported no significant net flow. Exact values and wallet counts were not provided.</li><li><strong>Unavailable:</strong> no usable data; never interpreted as zero.</li></ul><p>Cohorts can overlap. Transfers are not necessarily purchases. No price forecast or conviction score is implied.</p><p className="footnote">The boardroom fetches on page load and when you press Refresh. Nansen may cache its own response, and any cohort-specific warning means that cohort’s observation may be partial. Initial observations were retrieved through Nansen on Sep 25, 2026. Snapshot figures are rounded. The share card always uses 24 hours, even when you view seven days.</p><a className="source-link" href="https://docs.nansen.ai/api/token-god-mode/flow-intelligence" target="_blank" rel="noreferrer">Nansen documentation <ExternalLink size={14}/></a></DialogContent></Dialog>
 </div>;
}
